---
title: "Untitled"
output: html_document
date: "2025-05-11"
---


```{r setup, include=FALSE}
# Pakiety 
install.packages(c("tidyr", "readxl", "dplyr", "ggplot", "sf", "spdep", "sf", "spdep", "tmap", "tidyverse", "dplyr", "spatialreg"))
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
library(sf)
library(spdep)
library(tmap)
library(tidyverse)
library(dplyr)
library(spatialreg)
```

```{r setup, include=FALSE}
# Wczytywanie danych 
dane <- dane_panelowe_kopia
eu27 <- st_read("danemapy/EU27Official.shp")
```


```{r setup, include=FALSE}
# Dodawanie zmiennej Y w celu ułatwienia pisania 
dane_2024 <- dane %>% filter(rok == 2024)
# Wykres 1:  ~ Czas w unii europejskiej
q1 <- ggplot(dane_2024, aes(x = `Czas w unii europejskiej`, y = PPP)) +
  geom_point(color = "steelblue", size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_minimal() +
  labs(
    title = "Zależność PPP od Czasu w UE",
    x = "Czas w unii europejskiej",
    y = "PPP"
  )

# Wykres 2: Y ~ Ślad zużycia
q2 <- ggplot(dane_2024, aes(x = `Ślad zużycia`, y = Y)) +
  geom_point(color = "steelblue", size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_minimal() +
  labs(
    title = "Zależność PPP od Śladu zużycia",
    x = "Ślad zużycia",
    y = "P"
  )

# Wykres 3: Y ~ Electricity prices
q3 <- ggplot(dane_2024, aes(x = `Electricity prices`, y = Y)) +
  geom_point(color = "steelblue", size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_minimal() +
  labs(
    title = "Zależność PPP od Ceny energii elektrycznej",
    x = "Electricity prices",
    y = "PPP"
  )
# Wykres 4: Y ~ Jednostkowy koszt pracy
q4 <- ggplot(dane_2024, aes(x = `Jednostkowy koszt pracy`, y = Y)) +
  geom_point(color = "steelblue", size = 3) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  theme_minimal() +
  labs(
    title = "Zależność PPP od Jednostkowego kosztu pracy",
    x = "Jednostkowy koszt pracy",
    y = "PPP"
  )

``` 

```{r setup, include=FALSE}
# Wybór 
zmienne_do_korelacji <- dane_2024 %>%
  select(`PPP`,
         `Czas w unii europejskiej`,
         `Ślad zużycia`,
         `Electricity prices`,
         `Jednostkowy koszt pracy`)

# Obliczenie macierzy korelacji
macierz_korelacji <- cor(zmienne_do_korelacji, use = "complete.obs")

# Wyświetlenie wyniku
print(round(macierz_korelacji, 2))
```

```{r setup, include=FALSE}
# upewnij się, że oba są typu character
eu27$CNTR_ID <- as.character(eu27$CNTR_ID)
dane_panelowe$ID <- as.character(dane_panelowe$skr)

# teraz dopiero łączymy
eu27_merged <- left_join(eu27, dane_panelowe, by = c("CNTR_ID" = "skr"))

# Tworzymy relacje sąsiedztwa
neigh <- poly2nb(eu27_merged)

# Lista wag z normalizacją i obsługą brakujących sąsiadów
weights_list <- nb2listw(neigh, style = "W", zero.policy = TRUE)

# Podgląd liczby sąsiadów
table(card(neigh))
```

```{r setup, include=FALSE}
# Test globalny Morana
moran_global <- moran.test(eu27_merged$PPP, weights_list, zero.policy = TRUE)
print(moran_global)

# Wykres rozproszenia Morana
moran.plot(eu27_merged$PPP, weights_list, zero.policy = TRUE)

# Oblicz lokalny Moran I
local_moran <- localmoran(eu27_merged$PPP, weights_list, zero.policy = TRUE)

# Dodaj wyniki do mapy
eu27_merged$Ii <- local_moran[, "Ii"]
eu27_merged$Pvalue <- local_moran[, "Pr(z > 0)"]
eu27_merged$significant <- eu27_merged$Pvalue < 0.05
```
```{r setup, include=FALSE}
# Model klasyczny OLS
ols_model <- lm(PPP ~ `Electricity prices` + log(GDP) + `Jednostkowy koszt pracy` + `Średnie zarobki` + 
`Gęstość zaludnienia` + `Ślad zużycia` + `Czas w unii europejskiej`, data = eu27_merged)
summary(ols_model)

```

```{r setup, include=FALSE}
# Test autokorelacji przestrzennej reszt (ex-ante)
ols_resid <- residuals(ols_model)
moran.test(ols_resid, weights_list, zero.policy = TRUE)

```

```{r setup, include=FALSE}
library(spatialreg)
sar_model <- lagsarlm(GDP ~ UNEMP + RKONS, data = eu27_merged, listw = weights_list, zero.policy = TRUE)
summary(sar_model)

```








